FROM golang:1.21.1

WORKDIR /australia

COPY go.mod go.sum ./

RUN go mod download

COPY australia/names.txt ./
COPY australia/main.go ./

RUN go build -o australia_bin .

ENTRYPOINT [ "/australia/australia_bin" ]